var encodeURIComponent;
var decodeURIComponent;
Window.prototype.setTimeout;
Object.out;
Object.out.println;
Object.error;
Object.error.println;
Object.exec;
Object.index;
Object.install;
Int8Array.prototype.set;
Int8Array.prototype.fill;
Int8Array.prototype.length;
Int8Array.prototype.slice;
var Buffer;
Buffer.from;
var process;
process.hrtime;
var require;
Uint8Array.prototype.length;
var setTimeout;
RegExp.prototype.schema$core$Schema$;
RegExp.prototype.schema$core$Schema$spec$arity$1;
RegExp.prototype.schema$core$Schema$explain$arity$1;
var Java;
Java.type;
var S3;
S3.getObject;
S3.putObject;
